-- ==============================================================================
-- PROJECT NAME: Superstore Sales Data Analysis
-- TOOL USED: MySQL Workbench
-- PURPOSE: Extracting business insights from retail transactions
-- ==============================================================================

-- 1. Database and Table Context
USE sales_db;

-- ------------------------------------------------------------------------------
-- QUERY 1: Basic Financial Analysis
-- Business Question: What is the total sales revenue, total net profit, 
-- and the overall profit margin generated by the business so far?
-- ------------------------------------------------------------------------------
SELECT 
    ROUND(SUM(sales), 2) AS Total_Sales,
    ROUND(SUM(profit), 2) AS Total_Profit,
    ROUND((SUM(profit) / SUM(sales)) * 100, 2) AS Profit_Margin_Percentage
FROM samplesuperstore;


-- ------------------------------------------------------------------------------
-- QUERY 2: Customer Segmentation & High-Value Target Identification
-- Business Question: Who are the top 10 high-value customers based on their 
-- total spending, and how many orders have they placed?
-- ------------------------------------------------------------------------------
SELECT 
    customer_id,
    customer_name,
    segment,
    ROUND(SUM(sales), 2) AS Total_Spent,
    COUNT(DISTINCT order_id) AS Total_Orders
FROM samplesuperstore
GROUP BY customer_id, customer_name, segment
ORDER BY Total_Spent DESC
LIMIT 10;


-- ------------------------------------------------------------------------------
-- QUERY 3: Product Performance & Category Profitability
-- Business Question: Which product categories and sub-categories drive the 
-- highest sales volume, and which ones are facing losses?
-- ------------------------------------------------------------------------------
SELECT 
    category,
    sub_category,
    ROUND(SUM(sales), 2) AS Total_Sales,
    ROUND(SUM(profit), 2) AS Total_Profit,
    SUM(quantity) AS Total_Quantity_Sold
FROM samplesuperstore
GROUP BY category, sub_category
ORDER BY Total_Profit DESC;


-- ------------------------------------------------------------------------------
-- QUERY 4: Advanced Interview Level — Month-on-Month (MoM) Sales Growth Trend
-- Business Question: What is the month-on-month sales performance trend, 
-- and are there any significant revenue drops or seasonal growth spurts?
-- ------------------------------------------------------------------------------
WITH Monthly_Sales AS (
    SELECT 
        DATE_FORMAT(STR_TO_DATE(order_date, '%m/%d/%Y'), '%Y-%m') AS Sales_Month,
        SUM(sales) AS Current_Month_Sales
    FROM samplesuperstore
    GROUP BY DATE_FORMAT(STR_TO_DATE(order_date, '%m/%d/%Y'), '%Y-%m')
)
SELECT 
    Sales_Month,
    ROUND(Current_Month_Sales, 2) AS Current_Month_Sales,
    ROUND(LAG(Current_Month_Sales) OVER (ORDER BY Sales_Month), 2) AS Previous_Month_Sales,
    ROUND(((Current_Month_Sales - LAG(Current_Month_Sales) OVER (ORDER BY Sales_Month)) 
            / LAG(Current_Month_Sales) OVER (ORDER BY Sales_Month)) * 100, 2) AS MoM_Growth_Percentage
FROM Monthly_Sales;